version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    expose:
      - 20717
    networks:
      - gateway

  gateway:
    build: gateway
    restart: always
    environment:
      MONGODB_URL: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/"
    expose:
      - 8081
    networks:
      - gateway

  website:
    build: website
    restart: always
    environment:
      GATEWAY_URL: "http://gateway:8081"
    expose:
      - 8080
    networks:
      - gateway

  nginx:
    image: nginx
    restart: always
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80
    networks:
      - gateway

networks:
  gateway:
    external: false
